STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "title":          "Discord Image Grabber",
        "token_label":    "USER TOKEN",
        "channel_label":  "CHANNEL ID",
        "token_hint":     "Your Discord token",
        "channel_hint":   "Channel ID to grab images from",
        "choose_folder":  "Choose Folder",
        "no_folder":      "No folder selected",
        "download_btn":   "Download Images",
        "collecting":     "Collecting images…",
        "open":           "Open",
        "exit":           "Exit",
        "running_in_bg":  "Running in background",
        "tray_dl":        "Discord Image Grabber — downloading…",
        "done":           "Done! {} images downloaded.",
        "warning":        "Warning",
        "stop_exit":      "Download in progress. Stop and exit?",
        "choose_save":    "Choose Save Folder",
        "err_token":      "Invalid token. Check your Discord user token.",
        "err_channel":    "Channel not found or access denied.",
        "err_channel_fmt": "Channel ID must contain digits only.",
        "err_http":       "HTTP error: {}",
    },
    "ru": {
        "title":          "Загрузчик изображений Discord",
        "token_label":    "ТОКЕН ПОЛЬЗОВАТЕЛЯ",
        "channel_label":  "ID КАНАЛА",
        "token_hint":     "Ваш токен Discord",
        "channel_hint":   "ID канала для загрузки изображений",
        "choose_folder":  "Выбрать папку",
        "no_folder":      "Папка не выбрана",
        "download_btn":   "Скачать изображения",
        "collecting":     "Сбор изображений…",
        "open":           "Открыть",
        "exit":           "Выйти",
        "running_in_bg":  "Работает в фоне",
        "tray_dl":        "Загрузчик — загрузка…",
        "done":           "Готово! Загружено {} изображений.",
        "warning":        "Предупреждение",
        "stop_exit":      "Идёт загрузка. Остановить и выйти?",
        "choose_save":    "Выбрать папку для сохранения",
        "err_token":      "Неверный токен. Проверьте user-токен Discord.",
        "err_channel":    "Канал не найден или нет доступа.",
        "err_channel_fmt": "ID канала должен состоять только из цифр.",
        "err_http":       "Ошибка HTTP: {}",
    },
}
